"""Generates src/theme_table.zig, the built-in theme table, from Herdr's palettes.

Usage: python3 tools/gen-themes.py path/to/herdr/src/app/state.rs > src/theme_table.zig
       zig fmt src/theme_table.zig

Herdr (https://github.com/herdrdev/herdr, Apache-2.0) defines its themes in
`Palette::<name>()` functions. This script maps the tokens Kiwa draws with.
"""
import re
import sys

NAMED = {"Black": 0, "Red": 1, "Green": 2, "Yellow": 3, "Blue": 4, "Magenta": 5, "Cyan": 6, "Gray": 7,
         "DarkGray": 8, "LightRed": 9, "LightGreen": 10, "LightYellow": 11, "LightBlue": 12,
         "LightMagenta": 13, "LightCyan": 14, "White": 15}
# Kiwa token = Herdr token.
TOKENS = [("accent", "accent"), ("on_accent", "panel_bg"), ("panel", "panel_bg"), ("selected", "surface0"),
          ("text", "text"), ("muted", "subtext0"), ("heading", "overlay1"), ("divider", "surface1"),
          ("border", "surface1"), ("branch", "mauve"), ("marker", "yellow"), ("error", "red")]

src = open(sys.argv[1]).read()
order = re.findall(r'"([a-z-]+)" => Some\(Self::(\w+)\(\)\)', src)
out = ["//! Generated by tools/gen-themes.py from Herdr's palettes (Apache-2.0). Do not edit.",
       "const Theme = @import(\"theme.zig\").Theme;", "", "pub const herdr = [_]Theme{"]
for name, fn in order:
    body = re.search(r"pub fn %s\(\) -> Self \{\s*Self \{(.*?)\n\s*\}\s*\n\s*\}" % fn, src, re.S).group(1)
    fields = dict(re.findall(r"(\w+): Color::(\w+(?:\([^)]*\))?)", body))

    def color(tok):
        v = fields[tok]
        m = re.match(r"Rgb\((\d+), (\d+), (\d+)\)", v)
        if m:
            return ".rgb(%s, %s, %s)" % m.groups()
        if v == "Reset":
            return ".none"
        return ".palette(%d)" % NAMED[v]

    vals = {k: color(h) for k, h in TOKENS}
    # Herdr's terminal theme leaves surface0 at the default background.
    if vals["selected"] == ".none":
        vals["selected"] = color("active_row_bg")
    if vals["on_accent"] == ".none":
        vals["on_accent"] = ".palette(0)"
    out.append("    .{ .name = \"%s\", %s }," % (name, ", ".join(".%s = %s" % ("@\"error\"" if k == "error" else k, vals[k]) for k, _ in TOKENS)))
out.append("};")
print("\n".join(out))
